### ISSUE TITLE
Integrate TCP

### ISSUE THREAD

**Issue by danielleogden** [Trillium-Solutions/mendocino-wp-theme#32]
This was actualy part of the accessibility upgrade project and slipped by us! We still have plenty of budget for it (just stop doing any more work on the nice-to-have accessibility updates). If you have any questions, please work with @NomeQ to get this implemented.

**Comment by ekeaton** [comment]
@danielleogden TCP is now integrated into Mendo. One thing to note: Due to the current structure of their maps and service page. (With all the Routes in a custom order). Using tcp_list_routes() wouldn't work here. That function sorts routes by route sort order then list them out. So the Routes would be listed as Route 1, Route 5, etc. Which doesn't fit what they currently have. Ideally, it would be nice for this list to update with TCP, but I tried a few things and I tried creating a custom function that just checks if a Route exists but it still uses the sort order and Route 1 came first. 

Sooo, until we come up with another solution, I think the structure they have for now is okay. We'll just need to ask Support to activate Route 7. (it's currently not in service) So that link goes to the page. Then we can add a service alert to it, stating it's currently, not in service. 

Results on staging https://mdcinostaging.wpengine.com/

**Comment by danielleogden** [comment]
@NomeQ @evantrillium 
I didn't think about how this TCP integration was going to affect the route pages. Routes 7 & 9 are a multiroute and we wanted to keep their schedules and information on the same page. Have we done this in the past? The only site I can think of with multiroute is SCTransit. What can we do to accommodate this? _Should_ we accommodate this? Note that route 7 is not currently in service.

**Comment by evantrillium** [comment]
It's a separate field on SCTransit
route_page_id

**Comment by NomeQ** [comment]
SC Transit is a very frustrating system to maintain. I wouldn't recommend trying to re-create that here. We want to support multi-route in TCP, but we don't yet, and it's probably a significant chunk of work.

My thought for now would be to let 7 & 9 be separate route pages, and create an additional field for an info box on those pages, that links them together. E.g. a distinct info box on route 7 that says something like "[See schedules and information for Route 9](https://mendocinotransit.org/routes/routes-7-and-9/). Route 9 Ukiah Local connects..."

**Comment by evantrillium** [comment]
and here's hoping they don't bring 7 back at all - it was basically just 9 express, and the runs that were on 7 are actually *on* 9 right now. So I think maybe we just launch/move forward with 9, not worry about 7, and see what happens longterm with that route

**Comment by NomeQ** [comment]
Seems also like a good plan.

**Comment by ekeaton** [comment]
Okay so just to clarify. We are going to forgo having Route 7 at all within the site? Meaning the Maps and Schedules page should be updated to only show Route 9?

![Screen Shot 2021-03-30 at 1 06 56 PM](https://user-images.githubusercontent.com/43942870/113049768-e4666f00-9158-11eb-899c-a50e2141850e.png)

**Comment by danielleogden** [comment]
I'm going to check in with the client and will get back to you if they approve this change.

**Comment by danielleogden** [comment]
@ekeaton Client approves separate route pages. Route 7 will eventually come back but they're still not sure when. 
Looks like they already have a decent route description box, so I'm not sure we need to add anything. But one other thing I noticed on staging is that route 7 timetables link to route 75? Do you know what's up with that?

@evantrillium Luis says he's sorry it's taking him so long to complete the stop coordinates but he's still working on it!

**Comment by ekeaton** [comment]
@danielleogden Okay. So we're going to turn Route 7 back on in the gtfs? The current page on staging I just made within WP for testing. So it's not the real "route 7" from the gtfs. 

The test Route 7 page is most likely linking to Route 75 because there aren't any tt's for 7 so it's going for the next best number starting with 7. Similar to what we've seen on other sites with alerts on pages that start with the same number etc. I'll need to update the tt function to only show the tt buttons if tt's are available!

**Comment by danielleogden** [comment]
Let's keep the route 7 page up, hide the tts and add an alert to say that it's out of service.  

@evantrillium can we add route 7 back to the GTFS feed? Not urgent.

**Comment by evantrillium** [comment]
added 7 to routes.txt

**Comment by ekeaton** [comment]
@danielleogden All set on staging!

**Comment by danielleogden** [comment]
@ekeaton hmm something funky is going on with all the timetables. They cut off in the middle of the stop name
![Screen Shot 2021-04-02 at 3 13 34 PM](https://user-images.githubusercontent.com/31776892/113457938-0153aa00-93c6-11eb-9392-d2e646b410b4.png)

**Comment by ekeaton** [comment]
@danielleogden updated!

**Comment by danielleogden** [comment]
Route 9 tts running outside the box. (We can wrap this up next week btw if you're overtime! I'm also having issues with the lrta launch.)
![Screen Shot 2021-04-02 at 4 16 42 PM](https://user-images.githubusercontent.com/31776892/113460820-dd489680-93ce-11eb-92d0-49ad6d385e93.png)

**Comment by ekeaton** [comment]
@danielleogden fixed! Try a hard refresh if you're not seeing the changes, it was cached for me at first.

**Comment by danielleogden** [comment]
@ekeaton Ok, all good!

**Comment by ekeaton** [comment]
@danielleogden Updates are now on Production
