### ISSUE TITLE
Board Meetings post estimate

### ISSUE THREAD

**Issue by danielleogden** [Trillium-Solutions/mendocino-wp-theme#37]
Can you provide an hours estimate for what it would take to replace the current [board meetings functionality](https://mendocinotransit.org/board-of-directors/) with our newer Board Meetings post type? Like the one used for [BAT](https://www.ridebat.com/about-bat/board-meetings/)

**Comment by chancecorbeil** [comment]
I estimate 2-3 days, so 16-24 hours.

Here are some notes:
Set up Board Meetings CPT.
Set up Board Meeting fields in ACF.
Transfer 'board meeting' posts and fields to the Board Meetings CPT.
Build board Board Meetings archive template.
Build single Board Meeting post template.
Merge minutes to meetings Board Meeting posts.

Note: The URLs and url structure will change a bit.
Note: We can build a modern Board Meeting post template which contains the important fields, like NVTA, and all future Board Meeting posts will look good in that format. But past post pages might have a different layout since that data was formatted manually.

**Comment by danielleogden** [comment]
Can you explain more about this piece?

- Build board Board Meetings archive template.

Which pieces are the most time consuming? If it's the migration of old data, I wonder if the agency would be willing to "permanently archive" some of these really old meeting agendas and minutes. I'm curious what the hours estimate is for only setting up the new CPT and templates without any consideration of the old data?

**Comment by chancecorbeil** [comment]
> Can you explain more about this piece?
> 
> * Build board Board Meetings archive template.

Sure, that's how we make [this mendocino page](https://mendocinotransit.org/board-of-directors/) look and function more like [this BAT page](https://www.ridebat.com/about-bat/board-meetings/). We would be transferring and customizing the code.

> Which pieces are the most time consuming? If it's the migration of old data, I wonder if the agency would be willing to "permanently archive" some of these really old meeting agendas and minutes. I'm curious what the hours estimate is for only setting up the new CPT and templates without any consideration of the old data?

Yes, transferring the posts and data is very time consuming. Removing those tasks removes a day or more. estimate 7-14 hours.
